version: "3.3"

services:

  sandbox-postgresql:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-postgresql
    image: sandbox-postgresql
    volumes:
      - sql_files:/files:ro
      - ../src:/app/src
    ports:
      - "9004:9004"
    networks:
      - docker_localhost
    environment:
      - DEBUG=true
      - PSQL_USER=sandbox
      - PSQL_PASSWORD=sandbox
      - PSQL_PORT=5433
      - PSQL_HOST=sandbox-postgresql-db
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:9004 app.main:app --reload -w 1
    depends_on:
      - sandbox-postgresql-db

  sandbox-postgresql-db:
    container_name: sandbox-postgresql-db
    image: postgres:13
    networks:
      - docker_localhost
    volumes:
      - sql_files:/files:ro
      - ../postgresql-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
      POSTGRES_DB: sandbox
    restart: always


networks:
  docker_localhost:
    external: true

volumes:
  sql_files:
    external: true
  # монтирование к ФС невозможно т.к. требуется абсолютный путь
  # для получения доступа к файлам использовать путь
  # указанный в Mountpoint команды "docker inspect docker_sql_files"